### ISSUE TITLE
Issue with  1.2.2 for zabbix

### ISSUE THREAD

**Issue by farzadha2** [tiredofit/docker-restic#2]
Hi Dave,
Currently i had to drop down to version 1.2.1 as the change seems not sending to zabbix
This happens when i first create the repo 
Thanks

**Comment by tiredofit** [comment]
Solved with `1.2.3`

**Comment by farzadha2** [comment]
HI @tiredofit Quick question, i currently see this info but no data? could you remind me whats the manual command to send the info to zabbix?

![image](https://github.com/tiredofit/docker-restic/assets/62571297/eb7d4aaa-37b1-4c99-9993-c6c5fcd84674)

**Comment by tiredofit** [comment]
Backups get sent to Zabbix from here: https://github.com/tiredofit/docker-restic/blob/2b159b3213cf1a66c70dfd0a96dcc2e0f165654a/install/assets/functions/20-restic#L1197 - Since it's doing it silently you can activate `SHOW_OUTPUT=TRUE` which may give some information as to what is being sent or the results, or by cranking up the log level in your zabbix agent (4) and reading the logs when the information is being sent..
